# Generated by Django 3.0.5 on 2020-05-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
