# Generated by Django 3.0.5 on 2020-05-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=30)),
                ('values', models.CharField(max_length=255)),
                ('datatype', models.CharField(max_length=20)),
                ('mod_date', models.DateTimeField()),
            ],
        ),
    ]
